server:
  port: 5088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: config-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/405990230/server-demo.git #配置文件在github上的地址
          #Configserver会在 Git仓库根目录、 config-file子目录，以及所有以 bar开始的子目录中查找配置文件。
          search-paths: config-file,bar*
          #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库
          clone-on-start: true



